Add option to enable health check logging
terraform-google-modules/terraform-google-lb-internal pull request #49
Opened 2021-03-22 19:20 UTC by tnguyen14

2021-04-06 13:41 UTC, tnguyen14 commented
I tried using the `google-beta` provider, but the tests still failed. I am not sure why.

2021-04-06 17:21 UTC, morgante commented
The examples would also need to be updated.

2021-04-06 19:01 UTC, tnguyen14 commented
@morgante happy to update it once we can get this to work/ tests to pass.

2021-04-06 19:09 UTC, morgante commented
@tnguyen14 This won't pass until the examples are updated, because the tests use the examples.

2021-04-06 20:24 UTC, tnguyen14 commented
@morgante I tried to update the example, but it's still failing. Is there a way I can look at the error message to figure out what might be wrong?

2021-04-06 20:29 UTC, morgante commented
@tnguyen14 [This comment](https://github.com/terraform-google-modules/terraform-google-lb-internal/pull/49#issuecomment-812202759) gets updated with the latest results.

2021-04-06 21:01 UTC, tnguyen14 commented
Test is passing now.

2021-04-06 22:23 UTC, morgante requested changes

2021-04-06 22:23 UTC, morgante commented on main.tf
> +  log_config {
We should make this a dynamic block.

```suggestion
  dynamic "log_config" {
    for_each = var.health_check["enable_log"] ? [true] : []
    content {
      enable = true
    }
  }
```

2021-04-12 21:05 UTC, morgante approved these changes

2021-04-12 21:05 UTC, merged